### ISSUE TITLE
The server isnt starting

### ISSUE THREAD

**Issue by 410-ghost** [SoftbearStudios/kiomet#10]
[ERROR game_server::entry_point] https server stopped: Err(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
[ERROR game_server::infrastructure] infrastructure stopped

**Comment by Totzmaster** [comment]
The server wants to listen at the standard https port 443 but another process already opened the server socket.
Maybe you have already a webserver running?

**Comment by finnbear** [comment]
Totzmaster is correct; As a workaround, you can use [`--http-port 40000 --https-port 40001`](https://github.com/SoftbearStudios/kiomet/blob/8ea1060fe0e43cfb2731e37b61b2fb0c2f89c576/engine/game_server/src/options.rs#L49-L52) when running the server to use different ports

**Comment by 410-ghost** [comment]
oww yes 443 and 80 is used for nginx where do i modify thath tho

**Comment by finnbear** [comment]
You can try `cargo run -- --http-port 40000 --https-port 40001` or use those arguments on whatever other command you are using to run the game e.g. `./kiomet --http-port 40000 --https-port 40001`. If you want to expose the server via NGINX, you can use NGINX reverse proxy aka `proxy_pass`.

**Comment by 410-ghost** [comment]
now i have that error

[INFO  game_server::plasma] executing plasma request: Heartbeat { game_id: Kiomet, server_id: Local/25, player_count: 0, client_hash: 55335, unhealthy: false, cpu: 0.025064353, ram: 0.37880683 }
[WARN  game_server::plasma] <?xml version="1.0" encoding="iso-8859-1"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
             "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Not Found</title>
        </head>
        <body>
                <h1>404 - Not Found</h1>
                <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script>
        </body>
    </html>
     (code 404 Not Found)

**Comment by finnbear** [comment]
That's a WARNing and an INFOrmation, not an ERROR. Try navigating to the port you specified (`<server IP>:40000`).

**Comment by 410-ghost** [comment]
yeah i tried that maybe its the firewall because i cant acces the game
