### ISSUE TITLE
希望优化联盟的机制(Hope to optimize the mechanism of the alliance)

### ISSUE THREAD

**Issue by wowqaqtat** [SoftbearStudios/kiomet#4]
当我与其他玩家结成联盟时，希望我的视野可以增加，并且可以移动到盟友的领地。这样我们可以更快地向外扩张领地。
(When I form an alliance with other players, I hope my vision can increase and I can move to the territory of my allies. This way, we can expand our territory more quickly.)

否则当我周围都是盟友时，我便没有进攻目标。
(Otherwise, when I am surrounded by allies, I have no attack target.)

**Comment by finnbear** [comment]
Hello! The reason why the game doesn't give you the vision of your allies is if a giant player allied with everyone around them, then a huge number of players would see a huge amount of the world, causing bandwidth/lag issues. The reason why the game doesn't let you move your troops through your ally is that it could allow you to leap-frog them (gain territory on the other side of them), which boxes your ally in and also allows too many players to get too much far-away territory and end up seeing too much of the world area (again causing bandwidth/lag issues).

> Otherwise, when I am surrounded by allies, I have no attack target.

I suggest you avoid allying with *all* your neighbors. Or, once you want to attack, break at least one of the alliances.
