### ISSUE TITLE
请问如何帮助翻译？(How can I help with translation?)

### ISSUE THREAD

**Issue by wowqaqtat** [SoftbearStudios/kiomet#5]
我很喜欢你开发的这款游戏，我希望能更好地支持简体中文。这样可以帮助中国玩家玩这款游戏。
I **really** like the game you developed, and I hope it can better support Simplified Chinese. This can help Chinese players play this game.

我可以帮助翻译，但是我不太熟悉Rust语言。
I can help with translation, but I am not very familiar with the Rust language.

![translation1](https://github.com/SoftbearStudios/kiomet/assets/70186204/2ae4c696-fe00-4c5a-8d17-857e2d4266a7)

**Comment by finnbear** [comment]
Hello! We do take translation corrections but in text form, not image form. For example: https://github.com/SoftbearStudios/kiomet/issues/3#issue-1971991865
