### ISSUE TITLE
Error  E0793 when running "cargo install --locked trunk --version 0.15.0"

### ISSUE THREAD

**Issue by bobbyboi64** [SoftbearStudios/kiomet#9]
error[E0793]: reference to packed field is unaligned
    --> C:\Users\takus\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\takus\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `trunk v0.15.0`, intermediate artifacts can be found at `C:\Users\takus\AppData\Local\Temp\cargo-installR0Ewe5`

**Comment by finnbear** [comment]
Which `rustc` version did you use? If you use the one from the readme, by being in the same directory as you set the override, it has a higher chance of working.

**Comment by bobbyboi64** [comment]
rustc 1.71.0-nightly (f5559e338 2023-04-24)

**Comment by bobbyboi64** [comment]
Do I install trunk in any directory for in the project directory

**Comment by bobbyboi64** [comment]
Also how does the kiomet.com website work because you can right click without triggering the default tab and shortcuts don't work.

**Comment by finnbear** [comment]
Make sure you install `trunk` in a directory with that rust version (in general, do whatever our working CI build workflow does). If it doesn't work there, idk what I can do to help, though. `trunk` is a 3rd party tool. Maybe we could update to the latest version of `trunk` so it would compile on newer `rustc`.

Re: right click menu, that's just `element.addEventListener('contextmenu', e => e.preventDefault())`

**Comment by bobbyboi64** [comment]
Is it possible to make a web extension for the game?

**Comment by finnbear** [comment]
Not sure why we would want to create a browser extension for the game. It's already an installable [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).

**Comment by bobbyboi64** [comment]
is there a way to edit the PWA?

**Comment by finnbear** [comment]
Please describe what you mean by "edit" and what your goal is, so I can better understand

**Comment by bobbyboi64** [comment]
Im trying to look at the code of the game and maybe  make an algorithm to play the game

**Comment by bobbyboi64** [comment]
But I get the errors with trunk

**Comment by finnbear** [comment]
> Im trying to look at the code of the game and maybe make an algorithm to play the game
Easiest way is for you to modify and compile the game.

> But I get the errors with trunk
You could try again in a Linux environment. The error looks potentially Windows-related.

**Comment by bobbyboi64** [comment]
> > Im trying to look at the code of the game and maybe make an algorithm to play the game
> 
> Easiest way is for you to modify and compile the game.
> 
> > But I get the errors with trunk
> 
> You could try again in a Linux environment. The error looks potentially Windows-related.

if i recompile im banned from playing on official servers?

**Comment by bobbyboi64** [comment]
![image](https://github.com/SoftbearStudios/kiomet/assets/104128215/0f4b1992-b562-4d03-91c2-13a135e69da5)

**Comment by bobbyboi64** [comment]
why is this

**Comment by bobbyboi64** [comment]
![image](https://github.com/SoftbearStudios/kiomet/assets/104128215/416a0f29-82ad-449a-a1f9-36f0bab0eb48)

**Comment by bobbyboi64** [comment]
i installed the worng trunk

**Comment by bobbyboi64** [comment]
but following the readme.md gives errors for trunk not being a command

**Comment by bobbyboi64** [comment]
how did you do this?
